version: '3.7'
services:
    db:
        image: postgres:latest
        env_file: envs/dev.env
        ports:
            - 5432:5432
        volumes:
           - pgdata:/var/lib/postgresql/data  
    migration1:
        build: .
        env_file: envs/dev.env
        command: 
            bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py makemigrations'
        volumes:
            - .:/code
        depends_on:
            - db
    migration2:
        build: .
        env_file: envs/dev.env
        command: 
            bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py migrate'
        volumes:
            - .:/code
        depends_on:
            - db
            - migration1
    web:
        build: .
        env_file: envs/dev.env
        command: 
            bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python3 manage.py runserver 0.0.0.0:8000'
        volumes:
            - .:/code
        stdin_open: true
        tty: true
        ports:
            - 8000:8000

        depends_on: 
            - db
            - migration1
            - migration2

volumes: 
    pgdata:
        external: true